FIND_PATH(OpenLDAP_INCLUDE_DIR ldap.h /usr/include /usr/local/include)

FIND_LIBRARY(OpenLDAP_LIBRARY ldap /usr/lib /usr/local/lib)

IF (OpenLDAP_INCLUDE_DIR AND OpenLDAP_LIBRARY)
  SET(OpenLDAP_FOUND TRUE)
ENDIF(OpenLDAP_INCLUDE_DIR AND OpenLDAP_LIBRARY)


IF(OpenLDAP_FOUND)
  IF(NOT OpenLDAP_FIND_QUIETLY)
    MESSAGE(STATUS "Found OpenLDAP: ${OpenLDAP_LIBRARY}")
  ENDIF(NOT OpenLDAP_FIND_QUIETLY)
ELSE(OpenLDAP_FOUND)
  IF(OpenLDAP_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find OpenLDAP.")
  ENDIF(OpenLDAP_FIND_REQUIRED)
ENDIF(OpenLDAP_FOUND)

